### ISSUE TITLE
Earth?

### ISSUE THREAD

**Issue by zvezdochiot** [kbevers/gama#1]
Hi @cepek .

Interested in the possibility of bringing the zenith angles to the middle of the line along the average radius of the Earth:
```sh
#define defREarth 6370009.0
double atmospheric = 0.0, RE = defREarth;
z -= (RE > 0.0) ? (S * sin(z) * 0.5 / RE * (1.0 - atmospheric)) : 0.0;
```
Is there such or similar mechanism in `gama-local`? 
![Earth](https://studfile.net/html/2706/202/html_k4Dm2fAdJC.65QJ/htmlconvd-M26HUv_html_4086782ab0190d65.png)

**Comment by kbevers** [comment]
I suggest you ask this question on the project mailing list (more at https://www.gnu.org/software/gama/). This is just an unmaintained mirror of the software and is a bad place for discussing new ideas for Gama

**Comment by zvezdochiot** [comment]
Hi @kbevers .

I understand. But @cepek has too much scattered code. I see no point in participating in all these resources / mailing lists. And here it is quite possible to discuss this issue calmly and without inconvenience. If this brings you inconvenience, I apologize.

**Comment by kbevers** [comment]
>  I see no point in participating in all these resources / mailing lists. 

That's the projects form of communication, like it or not. I don't particularly agree with the arcane ways of the GNU people but that's not my battle to fight. I'll take down this repository tomorrow, I don't want to contribute to fragmenting what little of a community this project's got.

**Comment by zvezdochiot** [comment]
Hi @kbevers .

It's a pity.

**Comment by zvezdochiot** [comment]
https://github.com/orgs/Geo-Linux-Calculations/teams/gama-gui/discussions/1/comments/10
